# Generated by Django 5.2.7 on 2025-10-23 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Invoice document (PDF, JPG, PNG, or DOCX)', upload_to='invoices/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_time', models.FloatField(blank=True, help_text='Time taken for extraction in seconds', null=True)),
                ('schema_type', models.CharField(default='completo', help_text='Schema type used: completo or simplificado', max_length=50)),
                ('tipo_comprobante', models.CharField(blank=True, help_text='Document type (e.g., FACTURAS A, TIQUE FACTURA A)', max_length=100, null=True)),
                ('codigo_comprobante', models.CharField(blank=True, help_text='AFIP document code (e.g., 001, 006, 081)', max_length=10, null=True)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Invoice number (e.g., 0029-00271813)', max_length=100, null=True)),
                ('punto_venta', models.CharField(blank=True, help_text='Point of sale number', max_length=20, null=True)),
                ('fecha_emision', models.DateField(blank=True, help_text='Issue date', null=True)),
                ('cae', models.CharField(blank=True, help_text='CAE - Electronic Authorization Code', max_length=50, null=True)),
                ('fecha_vencimiento_cae', models.DateField(blank=True, help_text='CAE expiration date', null=True)),
                ('moneda', models.CharField(default='ARS', help_text='Currency code', max_length=10)),
                ('condicion_venta', models.CharField(blank=True, help_text='Payment terms', max_length=255, null=True)),
                ('empresa_razon_social', models.CharField(blank=True, help_text='Vendor business name', max_length=255, null=True)),
                ('empresa_cuit', models.CharField(blank=True, help_text='Vendor CUIT (Tax ID)', max_length=20, null=True)),
                ('empresa_condicion_iva', models.CharField(blank=True, help_text='Vendor VAT status', max_length=100, null=True)),
                ('empresa_domicilio', models.TextField(blank=True, help_text='Vendor address', null=True)),
                ('empresa_ingresos_brutos', models.CharField(blank=True, help_text='Vendor gross income tax number', max_length=50, null=True)),
                ('empresa_provincia', models.CharField(blank=True, help_text='Vendor province', max_length=100, null=True)),
                ('cliente_nombre', models.CharField(blank=True, help_text='Customer name or business name', max_length=255, null=True)),
                ('cliente_cuit', models.CharField(blank=True, help_text='Customer CUIT (Tax ID)', max_length=20, null=True)),
                ('cliente_condicion_iva', models.CharField(blank=True, help_text='Customer VAT status', max_length=100, null=True)),
                ('cliente_domicilio', models.TextField(blank=True, help_text='Customer address', null=True)),
                ('cliente_provincia', models.CharField(blank=True, help_text='Customer province', max_length=100, null=True)),
                ('subtotal_gravado', models.DecimalField(blank=True, decimal_places=2, help_text='Taxable subtotal before taxes', max_digits=15, null=True)),
                ('total_iva', models.DecimalField(blank=True, decimal_places=2, help_text='Total VAT/IVA amount', max_digits=15, null=True)),
                ('total_percepciones', models.DecimalField(blank=True, decimal_places=2, help_text='Total perceptions', max_digits=15, null=True)),
                ('total_retenciones', models.DecimalField(blank=True, decimal_places=2, help_text='Total withholdings', max_digits=15, null=True)),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total invoice amount', max_digits=15, null=True)),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total discounts', max_digits=15, null=True)),
                ('items_count', models.IntegerField(blank=True, help_text='Number of line items', null=True)),
                ('diferencia_matematica', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Arithmetic difference in calculations', max_digits=10, null=True)),
                ('raw_extraction', models.JSONField(blank=True, help_text='Complete extraction data from LlamaExtract in JSON format', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='invoice_ext_uploade_27838d_idx'), models.Index(fields=['status'], name='invoice_ext_status_f74e0c_idx'), models.Index(fields=['empresa_cuit'], name='invoice_ext_empresa_a6c7e7_idx'), models.Index(fields=['cliente_cuit'], name='invoice_ext_cliente_c8d2e6_idx'), models.Index(fields=['numero_comprobante'], name='invoice_ext_numero__fa74c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Product code or SKU (e.g., YPF-78005)', max_length=100, null=True)),
                ('descripcion', models.TextField(help_text='Product or service description')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Quantity (can be fractional, e.g., 43.0202)', max_digits=10)),
                ('unidad_medida', models.CharField(blank=True, help_text='Unit of measure (CJ=box, UN=unit, KG, LT, etc.)', max_length=50, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=4, help_text='Unit price per item before taxes', max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Line item subtotal (cantidad × precio_unitario)', max_digits=15)),
                ('order', models.IntegerField(default=0, help_text='Order/position of item in the invoice')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_extractor.invoice')),
            ],
            options={
                'verbose_name': 'Item de Comprobante',
                'verbose_name_plural': 'Items de Comprobantes',
                'ordering': ['order', 'id'],
            },
        ),
    ]
