# Generated by Django 5.2.7 on 2025-10-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='validation_score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Validation score from post-processing (0.0000 - 1.0000)', max_digits=5, null=True),
        ),
    ]
