# Generated by Django 5.2.7 on 2025-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_extractor', '0002_invoice_validation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extraction_method',
            field=models.CharField(choices=[('llama', 'LlamaExtract'), ('gemini', 'Gemini'), ('both', 'LlamaExtract + Gemini')], default='llama', help_text='Extraction method used', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gemini_improvement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score improvement from Gemini retry (percentage points)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gemini_retry_used',
            field=models.BooleanField(default=False, help_text='Whether Gemini retry was triggered'),
        ),
    ]
